### ISSUE TITLE
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require': cannot load such file -- ffi_c (LoadError)

### ISSUE THREAD

**Issue by aikomastboom** [Cj-bc/homebrew-sonic-pi-tool#2]
I guess this has to do with Sonic Pi changing its internals, as the current version of Sonic Pi 3.2.2 does not use the ruby server anymore?

```sh
$ sonic-pi-tool check
Sonic Pi server NOT listening on port 4557

$ sonic-pi-tool start-server
thread 'main' panicked at 'Unable to start /Applications/Sonic Pi.app/Contents/Resources/app/server/ruby/bin/sonic-pi-server.rb', src/lib.rs:111:48
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

$ RUST_BACKTRACE=1 sonic-pi-tool start-server
thread 'main' panicked at 'Unable to start /Applications/Sonic Pi.app/Contents/Resources/app/server/ruby/bin/sonic-pi-server.rb', src/lib.rs:111:48
stack backtrace:
   0: _rust_begin_unwind
   1: std::panicking::begin_panic_fmt
   2: lib::start_server::{{closure}}
   3: lib::start_server
   4: sonic_pi_tool::main
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

$ RUST_BACKTRACE=full sonic-pi-tool start-server
thread 'main' panicked at 'Unable to start /Applications/Sonic Pi.app/Contents/Resources/app/server/ruby/bin/sonic-pi-server.rb', src/lib.rs:111:48
stack backtrace:
   0:        0x1042fdc8e - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h0afb3dc3ec8cd05f
   1:        0x10432a73e - core::fmt::write::h39441ef24fae20ea
   2:        0x1042fda29 - std::io::Write::write_fmt::h2ffecc964e3c3ddd
   3:        0x104317a25 - std::panicking::default_hook::{{closure}}::h1a491655bcf6394f
   4:        0x10431774c - std::panicking::default_hook::h038c301fad559a62
   5:        0x104317f35 - std::panicking::rust_panic_with_hook::h489020cfd35413ea
   6:        0x1042fe4ab - std::panicking::begin_panic_handler::{{closure}}::he498abc45ca35fbf
   7:        0x1042fde08 - std::sys_common::backtrace::__rust_end_short_backtrace::h4a2a0fae6b0989d8
   8:        0x104317b13 - _rust_begin_unwind
   9:        0x10432fdab - std::panicking::begin_panic_fmt::h2f9eeaea76a9f06c
  10:        0x1042838e5 - lib::start_server::{{closure}}::h0ca6055c515f0575
  11:        0x104283698 - lib::start_server::h6184c3dff86a0216
  12:        0x10427d11a - sonic_pi_tool::main::h7653b64f4b05355c
  13:        0x10427b8fa - std::sys_common::backtrace::__rust_begin_short_backtrace::hc64c55f361bc05ed
  14:        0x10427b89c - std::rt::lang_start::{{closure}}::he4015e85b91f1322
  15:        0x10431819c - std::rt::lang_start_internal::h0a88825a8a52fb96
  16:        0x10427d739 - _main

$ ruby /Applications/Sonic\ Pi.app/Contents/Resources/app/server/ruby/bin/sonic-pi-server.rb
Traceback (most recent call last):
	14: from /Applications/Sonic Pi.app/Contents/Resources/app/server/ruby/bin/sonic-pi-server.rb:20:in `<main>'
	13: from /Applications/Sonic Pi.app/Contents/Resources/app/server/ruby/bin/sonic-pi-server.rb:20:in `require_relative'
	12: from /Applications/Sonic Pi.app/Contents/Resources/app/server/ruby/lib/sonicpi/studio.rb:16:in `<top (required)>'
	11: from /Applications/Sonic Pi.app/Contents/Resources/app/server/ruby/lib/sonicpi/studio.rb:16:in `require_relative'
	10: from /Applications/Sonic Pi.app/Contents/Resources/app/server/ruby/lib/sonicpi/samplebuffer.rb:17:in `<top (required)>'
	 9: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	 8: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	 7: from /Applications/Sonic Pi.app/Contents/Resources/app/server/ruby/vendor/ruby-aubio-0.3.3/lib/aubio.rb:2:in `<top (required)>'
	 6: from /Applications/Sonic Pi.app/Contents/Resources/app/server/ruby/vendor/ruby-aubio-0.3.3/lib/aubio.rb:2:in `require_relative'
	 5: from /Applications/Sonic Pi.app/Contents/Resources/app/server/ruby/vendor/ruby-aubio-0.3.3/lib/aubio/aubio-ffi.rb:3:in `<top (required)>'
	 4: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	 3: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	 2: from /Applications/Sonic Pi.app/Contents/Resources/app/server/ruby/vendor/ffi-1.11.3/lib/ffi.rb:4:in `<top (required)>'
	 1: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require': cannot load such file -- 2.6/ffi_c (LoadError)
	15: from /Applications/Sonic Pi.app/Contents/Resources/app/server/ruby/bin/sonic-pi-server.rb:20:in `<main>'
	14: from /Applications/Sonic Pi.app/Contents/Resources/app/server/ruby/bin/sonic-pi-server.rb:20:in `require_relative'
	13: from /Applications/Sonic Pi.app/Contents/Resources/app/server/ruby/lib/sonicpi/studio.rb:16:in `<top (required)>'
	12: from /Applications/Sonic Pi.app/Contents/Resources/app/server/ruby/lib/sonicpi/studio.rb:16:in `require_relative'
	11: from /Applications/Sonic Pi.app/Contents/Resources/app/server/ruby/lib/sonicpi/samplebuffer.rb:17:in `<top (required)>'
	10: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	 9: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	 8: from /Applications/Sonic Pi.app/Contents/Resources/app/server/ruby/vendor/ruby-aubio-0.3.3/lib/aubio.rb:2:in `<top (required)>'
	 7: from /Applications/Sonic Pi.app/Contents/Resources/app/server/ruby/vendor/ruby-aubio-0.3.3/lib/aubio.rb:2:in `require_relative'
	 6: from /Applications/Sonic Pi.app/Contents/Resources/app/server/ruby/vendor/ruby-aubio-0.3.3/lib/aubio/aubio-ffi.rb:3:in `<top (required)>'
	 5: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	 4: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	 3: from /Applications/Sonic Pi.app/Contents/Resources/app/server/ruby/vendor/ffi-1.11.3/lib/ffi.rb:3:in `<top (required)>'
	 2: from /Applications/Sonic Pi.app/Contents/Resources/app/server/ruby/vendor/ffi-1.11.3/lib/ffi.rb:6:in `rescue in <top (required)>'
	 1: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require': cannot load such file -- ffi_c (LoadError)
```

**Comment by Cj-bc** [comment]
I think this is related to [this issue on sonic-pi-tool](https://github.com/lpil/sonic-pi-tool/issues/32), and this formula repository does not have anything to do.
Please refer to that repo :)

**Comment by aikomastboom** [comment]
reverting back to Sonic Pi 3.1.0 got it working for me.. https://github.com/sonic-pi-net/sonic-pi/releases/tag/v3.1.0
